language: node_js
node_js:
- '4'
- 'node'
sudo: false
services:
- docker
- mongodb
script:
- npm run bootstrap
- npm run lint
- npm run test-ci
cache:
  directories:
    - node_modules
    - demo/server/node_modules
    - cloud/logger/node_modules
    - cloud/passportauth/node_modules
    - cloud/datasync/node_modules
    - cloud/wfm-rest-api/node_modules
    - cloud/wfm-user/node_modules
    - client/logger/node_modules
    - client/wfm/node_modules
    - client/datasync-client/node_modules
